# Generated by Django 4.2.7 on 2024-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counted_veiws',
            field=models.IntegerField(default=0),
        ),
    ]
