# Generated by Django 4.2.7 on 2024-02-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_date_post_published_date_post_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contex',
            new_name='content',
        ),
    ]
