# Generated by Django 4.2.7 on 2024-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_contex_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_veiws',
            field=models.IntegerField(default=0),
        ),
    ]
