# Generated by Django 4.2.7 on 2024-02-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/NaNN.jpg', upload_to='blog/'),
        ),
    ]
