# Generated by Django 4.2.7 on 2024-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='blog/NaNN_TraECc1.jpg', upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='none', to='blog.category'),
        ),
    ]
