# Generated by Django 4.2.7 on 2024-02-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated',
            new_name='updated_date',
        ),
    ]
