# Generated by Django 4.2.7 on 2024-02-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_created_contact_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
